[iOS] RewindJourney Scene
boostcampwm2023/iOS01-MusicSpot pull request #110
Opened 2023-11-24 04:10 UTC by PushedGun

## ❗ 배경
> 작업 배경에 대한 설명을 작성합니다.
> Issue에 대한 링크를 첨부합니다.
#83 

## 🔧 작업 내역
> 작업한 내용들을 나열합니다.
> 간결하게 리스트 업하고, 자세한 설명은 아래 리뷰 노트에서 합니다.
### MSMusicView
### RewindJourneyViewController
### MSProgressView

## 🧪 테스트 방법
> 동작을 테스트할 수 있는 방법을 설명합니다.
> 앱 실행 방법일 수 있고, 유닛 테스트 실행 방법일 수 있습니다.

### 사용 예제
이미지를 외부에서 주입받아, 주입받은 이미지들을 차례대로 띄워주도록 하였습니다.

```swift
    let vc = RewindJourneyViewController()
    vc.images = [UIImage(systemName: "pencil")!, UIImage(systemName: "pencil.circle")!, UIImage(systemName: "pencil.circle.fill")!]
    return vc
```

## 📝 리뷰 노트
> 작업 내역에 대한 자세한 설명을 작성합니다.
### MSMusicView
: 대략 프레임만 맞추어두었습니다. 후에 음악이 들어간 후 정밀하게 맞추는 작업이 필요할 수도 있습니다.

### RewindJourneyViewController
: 오른쪽과 왼쪽 뷰를 두어, 클릭하여 다른 이미지로 전환할 수 있게 구현하였습니다.

### MSProgressView
: 추후 유연성있게 사용하기 위해 커스텀하였습니다.

## 📸 스크린샷
> 작업한 내용에 대한 스크린샷, 영상 등을 첨부합니다.
![화면 기록 2023-11-24 오후 12 49 25](https://github.com/boostcampwm2023/iOS01-MusicSpot/assets/111111595/2b492996-80be-416e-82ad-e2254dcf2532)![화면 기록 2023-11-24 오후 12 50 41](https://github.com/boostcampwm2023/iOS01-MusicSpot/assets/111111595/475f8749-5f48-4f92-b6c6-3b031f199c99)

2023-11-26 05:29 UTC, SwiftyJunnos requested changes
고생하셨습니다!

전체적으로 Lint 적용이 안되어 있는 것 같아요.
한 번 적용하고 수정 부탁드립니다 😊

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
> +    private enum Metrix {
```suggestion
    private enum Metric {
```

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
> +        }
이 친구들 상수라서 `static let`으로 사용해도 될 것 같습니다.

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
> +    private var playTimeLabel = UILabel()
이 친구들도 Component 자체를 갈아끼우는 일은 없을 것 같아서
`let`으로 설정해줘도 될 것 같아요!

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
> +        MSFont.registerFonts()
`registerFonts()`는 SceneDelegate에서 한 번만 해주세요..!

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
> +    private var titleView = UIStackView()
```suggestion
    private let titleStack = UIStackView()
```

StackView는 프로퍼티 명에 Stack이 명시적으로 들어가면 좋을 것 같습니다.

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
> +    private var playTimeView = UIStackView()
```suggestion
    private let playTimeStack = UIStackView()
```

여기두요!

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/RewindJourneyViewController.swift
> +    // MARK: - Properties
```suggestion
    // MARK: - UI Components
```

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/RewindJourneyViewController.swift
> +
```suggestion
    
    // MARK: - Properties
    
```

MARK 주석 용도가 조금 헷갈릴 수 있겠네요..
노션 문서 업데이트 해두겠습니다 😅

https://www.notion.so/musicspot/Swift-c80e89fdf4ee41209c7afaed3d759e82?pvs=4#2ca9bc36ba1640939eb82712e2db8b65

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
MSMusicView랑 MSProgressView는 MSUIKit에 넣어도 될 것 같은데 어떻게 생각하시나요?

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSProgressView.swift
> +    }
이 두 가지 프로퍼티는 내부에서만 사용되는 것 같은데 왜 `public`인걸까요?

2023-11-26 05:29 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/RewindJourneyViewController.swift
> +            self.preHighlightenProgressView = self.progressViews?[index]
리뷰 노트를 보니 임시 처리인 것 같긴 하지만
인덱스 접근은 그래도 안전장치를 하나씩 마련해두면 좋을 것 같습니다.

`progressViews`의 count가 `index - 1`보다 크거나 작은 지 확인하는 정도로요..!

2023-11-26 05:31 UTC, SwiftyJunnos commented
지금 두 번째 사진으로 넘어가면 두 번째 Indicator만 하얗게 tint 처리되고 있는데
인스타 스토리처럼 그 이전 Indicator들도 하얗게 처리해주시면 좋을 것 같습니다!

2023-11-27 08:35 UTC, PushedGun commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/RewindJourneyViewController.swift
> +            self.preHighlightenProgressView = self.progressViews?[index]
앗 안전장치는 아래 코드에 해두었습니다!    

    ```swift
    @objc private func leftTouchViewTapped() {
        guard let presentImageIndex else {
            return
        }
        if presentImageIndex > 0 {
            let index = presentImageIndex - 1
            self.presentImageIndex = index
        }
    }

    @objc private func rightTouchViewTapped() {
        guard let images, let presentImageIndex else {
            return
        }
        if presentImageIndex < images.count - 1 {
            let index = presentImageIndex + 1
            self.presentImageIndex = index
        }
    }
```

2023-11-27 13:13 UTC, SwiftyJunnos requested changes

2023-11-27 13:13 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSProgressView.swift
> +    internal var isHighlight: Bool = false {
`isHighlighted`가 뭔가 문법 상 더 적절할 것 같습니다.

2023-11-27 13:13 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSProgressView.swift
> +        fatalError("MusicSpot은 code-based 로 개발되었습니다.")
```suggestion
        fatalError("MusicSpot은 code-based로만 작업 중입니다.")
```

이것도 통일할까요 😋

2023-11-27 13:13 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSProgressView.swift
> +    }
이 함수는 `public`으로 해야하지 않을까요?

2023-11-27 13:13 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
> +        self.albumArtView.backgroundColor = .blue
```suggestion
        self.albumArtView.backgroundColor = .msColor(.secondaryBackground)
```

2023-11-27 13:13 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
> +    private enum Metric {
상수들 `let`으로 변경해주세요..!

2023-11-28 02:15 UTC, PushedGun commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSProgressView.swift
> +        fatalError("MusicSpot은 code-based 로 개발되었습니다.")
해당 내용 swift 컨밴션에 추가해두겠습니다.

2023-11-28 02:16 UTC, PushedGun commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSProgressView.swift
> +    }
percentage에 따라 바 모양을 바꾸어주는 함수입니다.
private으로 내부에서만 사용되어야하는 함수가 맞습니다.

2023-11-28 02:18 UTC, PushedGun commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
> +    private enum Metric {
이건.. 죄송합니다

2023-11-28 02:27 UTC, PushedGun commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSMusicView.swift
> +        self.albumArtView.backgroundColor = .blue
이미지를 추가하면 사용자에겐 보이지 않으나 
다른 분이 저 albumArtView를 작업했을 때, 해당 View의 범위를 시각적으로 보일 수 있게 임의 색상값을 주었습니다.

생각해보니, 이 부분에서 지우고 Preview 코드에 색상값을 주는 코드를 추가해 가시적으로 하면 좋을 것 같네요!
피드백 감사합니다.

2023-11-28 05:20 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSProgressView.swift
> +    }
아 그러면 `isHighlighted` 프로퍼티로 패키지 내부에서만 조정하는건가 보군요?
실제로 동작은 투명한 버튼 두개로 하는거고..!?

2023-11-28 07:20 UTC, PushedGun commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSProgressView.swift
> +    }
아 넵 맞습니다!

2023-11-28 07:22 UTC, SwiftyJunnos commented on iOS/Features/RewindJourney/Sources/RewindJourneyView/MSProgressView.swift
> +    }
넵 알겠습니다
확인했습니다!

2023-11-30 12:35 UTC, closed without merging