[iOS] 여정 드로잉에 필요한 filter를 평균값을 활용하도록 수정
boostcampwm2023/iOS01-MusicSpot pull request #315
Opened 2023-12-13 00:58 UTC by yoondj98

## ❗ 배경
> 작업 배경에 대한 설명을 작성합니다.
> Issue에 대한 링크를 첨부합니다.

기존의 여정 위치 필터링 방식을 변경

## 🔧 작업 내역
> 작업한 내용들을 나열합니다.
> 간결하게 리스트 업하고, 자세한 설명은 아래 리뷰 노트에서 합니다.

기존에 적용하던 5m<이동거리<50m인 데이터만 반영하는 필터링 방식이 문제가 있어서 새로 평균값 필터를 적용했습니다.

## 🧪 테스트 방법
> 동작을 테스트할 수 있는 방법을 설명합니다.
> 앱 실행 방법일 수 있고, 유닛 테스트 실행 방법일 수 있습니다.

## 📝 리뷰 노트
> 작업 내역에 대한 자세한 설명을 작성합니다.

### 문제 인식

- 기존에는 여정에서 Coordinate를 찍는 방식을 단순히 5초동안 이전 위치로부터 5m<distatance<50m인지 여부를 기준으로 벗어나는 값들에 대해 필터링을 거쳤습니다.
- 하지만 한번 이 필터를 벗어날 경우 이후로 안찍히는 이슈가 발생할 수 있었습니다.
- 예를 들면 5초동안 4m를 이동하면 필터링으로 인해 움직이지 않았다고 판단을 하게 되고 그 다음의 5초동안 48m를 이동하면 filter는 52m를 이동했다고 인지해서 걸러버립니다.
- 이후로는 계속해서 받아오는 위치들을 모두 필터링함으로서 정상적인 이동거리(5m<distance<50m)임에도 불구하고 걸러버리게 됩니다.
- 이에 대한 개선을 위해 처음에는 Kalman Filter를 활용하고자 했습니다.

### Kalman 필터의 필요성
- 데이터들이 정확한 값에서 벗어니는 이슈들을 보정을 통해 최대한 정상적인 값에 가깝게 적용되도록 함.
- MusicSpot에서는 해당 위치를 통해 짧은 거리의 오차를 줄일 수가 있음.

### Kalman 필터의 문제점
- 해당 필터를 거친다고 모든 보정이 이뤄질 수가 없음을 인지
- 해당 필터는 표본이 쌓이는 과정을 통해 더욱 정확한 보정을 할 수 있지만 이런 Data Stacking 특성이 오히려 문제가 발생할 수 있음.
-> ex) 데이터 내에 현재 위치로부터 많이 튀는 위치(ex) 서울 중심에서 사용 중이다가 갑자기 경기도로 찍히는 경우)가 잡히는 순간 그 이후로 받아오는 데이터들이 이 필터를 거칠 시 모두 해당 오차를 적용한 채 위치를 찍기에 오히려 잘못된 위치가 계속해서 나오게 됨.

이러한 문제가 존재하기에 Kalman 필터의 적용보다 더 나은 방식을 모색했습니다.

### 평균값 필터의 활용
- **일정한 개수의 데이터를 받아와서 평균을 낸 후 해당 평균으로부터 가장 먼 데이터를 drop하는 방식**을 적용함.
- 매번 일정한 개수의 데이터를 새로 표본으로 두어 반영하기에 한번의 필터링 이슈가 이후의 데이터 필터에 영향을 끼치지 않음.
- 
## 📸 스크린샷
> 작업한 내용에 대한 스크린샷, 영상 등을 첨부합니다.

2023-12-13 03:41 UTC, PushedGun submitted a review, later dismissed
오 코드가 생각보다 복잡하지 않아 읽기 좋군요..?

많은 고민을 해주신 것이 보입니다!
발표에 사용해도 괜찮을 것 같아요.

2023-12-13 04:14 UTC, SwiftyJunnos requested changes
수고하셨습니다!
데이터 흐름이 조금 정리가 안되어 있어서 그 부분 수정만 해주시면 될 것 같습니다.

평균 필터 성능 테스트 같은 걸 적극적으로 해보고 싶은데 조금 아쉽네요..
부캠 기간 끝나고 다양한 필터들 한 번 도전해봐요..!

2023-12-13 04:14 UTC, SwiftyJunnos commented on iOS/Features/Home/Sources/NavigateMap/Presentation/RecordJourney/RecordJourneyViewModel.swift
> +        }
```suggestion
        if let previousCoordinate = self.state.previousCoordinate.value,
           calculateDistance(from: previousCoordinate, to: coordinate) <= 5 {
            return
        }
```

2023-12-13 04:14 UTC, SwiftyJunnos commented on iOS/Features/Home/Sources/NavigateMap/Presentation/Common/MapViewController.swift
> +        recordJourneyViewModel.trigger(.locationsShouldRecorded([filteredCoordinate2D]))
이 부분은 `state`의 값을 가져와서 다시 `trigger` 할거라면
이 부분이 아니라 다른 ViewModel 내부나 `bind` 함수쪽에서 하는 것이 더 좋아보입니다.

2023-12-19 18:13 UTC, PushedGun approved these changes

2024-01-23 00:01 UTC, SwiftyJunnos approved these changes

2024-01-23 00:04 UTC, merged