[iOS] MSNetworking 모듈 추가
boostcampwm2023/iOS01-MusicSpot pull request #69
Opened 2023-11-17 07:54 UTC by PushedGun

## ❗ 배경
> 작업 배경에 대한 설명을 작성합니다.
> Issue에 대한 링크를 첨부합니다.
#30 

## 🔧 작업 내역
> 작업한 내용들을 나열합니다.
> 간결하게 리스트 업하고, 자세한 설명은 아래 리뷰 노트에서 합니다.
### Network 모듈 생성 및 계층화

## 🧪 테스트 방법
> 동작을 테스트할 수 있는 방법을 설명합니다.
> 앱 실행 방법일 수 있고, 유닛 테스트 실행 방법일 수 있습니다.
### 1. baseURL, pathURL 추가
```swift
enum APIbaseURL: String {
    
    //base URL 추가 ex) case login = "https://로그인주소/"
    case none = ""
}

enum APIpathURL: String {
    
    //path URL 추가 ex) case idlist = "아이디리스트주소/"
    case none = ""
}
```
기능에 맞게 url 경로를 추가한 후, 저장된 데이터에 맞는 이름을 정해줍니다.

### 2. Router 설정

```swift
struct RouterType {
    
    private var encodable: Encodable?
    
    //기능별 Router
    var getJourney: Router {
        Router(baseURL: .none, pathURL: .none, method: .get, body: HTTPBody(content: encodable))
    }
    var getPerson: Router {
        Router(baseURL: .none, pathURL: .none, method: .get, body: HTTPBody(content: encodable))
    }
    
}
```
기능에 맞는 이름을 가진 Router 변수를 설정해줍니다.

### 3. 사용

```swift
//사용 에제 data를 전달해야 하는 경우
//
let mockRouterType = MockRouterType(encodable: data)

//publisher로 보냄
mockNetworking.request(mockRouter: mockRouterType.(보낼 라우터 변수 명), type: (받은 데이터 타입))

//해당 data를 받아야하는 부분에서 subscriber을 만들어 data를 받음

```

## 📝 리뷰 노트
> 작업 내역에 대한 자세한 설명을 작성합니다.
### DTO 생성
![스크린샷 2023-11-17 오후 4 52 41](https://github.com/boostcampwm2023/iOS01-MusicSpot/assets/111111595/8fceae63-b95e-4108-809c-180d2ac948c0)

보다 작은 단위의 DTO는 fragment라는 폴더를 두어 분류해두었습니다.

### Network 계층화
![스크린샷 2023-11-17 오후 4 53 19](https://github.com/boostcampwm2023/iOS01-MusicSpot/assets/111111595/e1ca843a-332f-4dac-a769-2dc5d3118377)

여러 계층을 두어, 다양한 형태의 API를 받을 수 있도록 하였습니다.

## 📸 스크린샷
> 작업한 내용에 대한 스크린샷, 영상 등을 첨부합니다.

2023-11-17 09:09 UTC, SwiftyJunnos commented
민건님 달리시는군요 🙌
마클 끝나고 바로 보겠습니다 ㅎㅎ

2023-11-17 09:10 UTC, SwiftyJunnos commented on .DS_Store
엥 `.DS_Store`가 왜 살아있을까요...?

2023-11-17 09:22 UTC, PushedGun commented on .DS_Store
엥 진짜네요

아마 iOS 상위 폴더에 gitignore이 빠져서 그런가..

2023-11-17 09:22 UTC, PushedGun commented on .DS_Store
엥 진짜네요

아마 iOS 상위 폴더에 gitignore이 빠져서 그런가..

2023-11-17 09:24 UTC, SwiftyJunnos commented on .DS_Store
아! 그러겠네요;;
이 PR 내에서 추가해주실 수 있을까요?

2023-11-17 09:31 UTC, PushedGun commented on .DS_Store
넵 ^^77

2023-11-17 10:51 UTC, SwiftyJunnos requested changes
DTO쪽은 일단 간단하게 작성하신 것 같아서
눈에 딱 보이는 점만 남겨두었습니다..!

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/DTO/Fragment/CoordinateDTO.swift
> +//
이 부분 전체적으로 수정 부탁드려요..!

```swift
//
//  파일명
//  프로젝트 / 패키지 명
//
//  작성자
```

컨벤션에 추가를 해둬야겠네요..

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/DTO/Fragment/SpotDTO.swift
> +    let spotIdentifier: UUID
DTO 구조체에 `Identifiable` 프로토콜을 채택하고
공통적으로 `id` 프로퍼티로 통일 시켜주는건 어떨까요?

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/MSNetworking.swift
> +    func request<T: Decodable>(requestable: Requestable, type: T.Type) -> AnyPublisher<T, Error>? {
Combine을 사용하셨네요..!
Swift Concurrency로도 가능했을 것 같은데 의사 결정의 이유가 궁금합니다.

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/MSNetworking.swift
> +struct MSNetworking {
이 친구 아마 `public`으로 오픈해줘야 할 것 같습니다.

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/MSNetworking.swift
> +                let value = try JSONDecoder().decode(T.self, from: result.data)
HTTPBody에서 `JSONEncoder`를 프로퍼티로 빼서 사용해주고 계시던데
여기서도 동일하게 해보는 게 어떨까요?

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/Protocol/Requestable.swift
> +    var pathURL: APIpathURL { get }
```suggestion
    var baseURL: APIBaseURL { get }
    var pathURL: APIPathURL { get }
```

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Tests/MSNetworkingTests/MSNetworkingTests.swift
> +                XCTAssertNotNil(JourneyDTO)
앗..
Combine의 sink는 단순히 스트림을 만들어 줄 뿐이라서
아마 이렇게 넣으시면 무조건 성공한다고 뜰거에요..!

`XCTestExpectation`과 같은 비동기 테스팅 방식을 사용해주셔야 합니다..

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSFoundation/Sources/MSLogger/MSLogger.swift
> +MSLogger.make(category: .network).
이거 보여주시려고 쳤다가 그대로 포함된 것 같습니다 ㅎㅎ

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/Router.swift
> +struct Router: Requestable {
```suggestion
struct MSRouter: Router {
```

뭔가 네이밍이 어색한 것 같은데 이건 어떠신가요? 👀

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Tests/MSNetworkingTests/Mock/MockMSNetworking.swift
> +    }
이 Mock 파일이 실제 사용 방식과 비슷하다고 보면 되는걸까요?
한 번 설명회 열어주시죠~!

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/DTO/JourneyDTO.swift
> +    let JourneyIdentifier: UUID
```suggestion
    let journeyIdentifier: UUID
```

2023-11-17 10:51 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/DTO/PersonDTO.swift
> +    let Journeys: [JourneyDTO]
```suggestion
    let journeys: [JourneyDTO]
```

2023-11-17 11:25 UTC, PushedGun commented on iOS/MSCoreKit/Sources/MSNetworking/DTO/Fragment/CoordinateDTO.swift
> +//
//  MSFetcher.swift
//  MSCoreKit
//
//  Created by 이창준 on 11/14/23.

이런 느낌으로 말이죠?
알겠습니다!

2023-11-17 11:31 UTC, PushedGun commented on iOS/MSFoundation/Sources/MSLogger/MSLogger.swift
> +MSLogger.make(category: .network).
앗.. 죄송합니다.

2023-11-17 11:32 UTC, PushedGun commented on iOS/MSCoreKit/Sources/MSNetworking/DTO/Fragment/SpotDTO.swift
> +    let spotIdentifier: UUID
그것도 좋은 방법 같습니다.
참고로 DTO는 사실 BE 분들과 겹치는 영역이라 일단은 아이디어 뱅크에 생성되어 있는 내용 그대로 작성했어요!

2023-11-17 11:38 UTC, PushedGun commented on iOS/MSCoreKit/Sources/MSNetworking/MSNetworking.swift
> +                let value = try JSONDecoder().decode(T.self, from: result.data)
반대로 생각해보니, 굳이 프로퍼티로 뺄 이유가 없을 것 같아요.
HTTPBody 구조체의 크기만 커지는 것 같습니다.

오히려 HTTPBody에서 프로퍼티로 빼던 걸 지워야하는 게 좋을 것 같은데 창준님 의견은 어떠신가요?

2023-11-17 11:43 UTC, PushedGun commented on iOS/MSCoreKit/Sources/MSNetworking/Router.swift
> +struct Router: Requestable {
이런 피드백 너무 좋습니다. 감사합니다!

2023-11-17 11:44 UTC, PushedGun commented on iOS/MSCoreKit/Tests/MSNetworkingTests/Mock/MockMSNetworking.swift
> +    }
맞습니다.. 사실 테스트할 목적도 있지만, 그보단 메뉴얼 같은 느낌으로 쓰려고 했어요.

2023-11-17 11:52 UTC, PushedGun commented on iOS/MSCoreKit/Sources/MSNetworking/MSNetworking.swift
> +    func request<T: Decodable>(requestable: Requestable, type: T.Type) -> AnyPublisher<T, Error>? {
1. 저희 기술 스택을 combine으로 정하고 시작하였기에 다른 영역을 작업하시는 분이 combine을 쓰실 것 같아 combine으로 맞춰 작업하였습니다.

2. 비동기 매체를 통일시키고 싶었어요. 어느 부분에선 concurrency, 어느 부분에선 combine이면 읽는 사람 입장에서 조금 어색할 수도 있을 것 같았습니다.

2023-11-17 11:52 UTC, PushedGun commented on iOS/MSCoreKit/Sources/MSNetworking/MSNetworking.swift
> +    func request<T: Decodable>(requestable: Requestable, type: T.Type) -> AnyPublisher<T, Error>? {
1. 저희 기술 스택을 combine으로 정하고 시작하였기에 다른 영역을 작업하시는 분이 combine을 쓰실 것 같아 combine으로 맞춰 작업하였습니다.

2. 비동기 매체를 통일시키고 싶었어요. 어느 부분에선 concurrency, 어느 부분에선 combine이면 읽는 사람 입장에서 조금 어색할 수도 있을 것 같았습니다.

2023-11-18 15:14 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/MSNetworking.swift
> +    func request<T: Decodable>(requestable: Requestable, type: T.Type) -> AnyPublisher<T, Error>? {
하나로 정해서 그것만 사용하기보다는 각 상황에 맞게 사용하는 것이 좋을 것 같아요!

Concurrency는 단발성의 병렬 작업이 필요한 경우,
Combine은 한 쌍의 연결에 지속적인 데이터 교환이 일어나는 경우 쓸 수 있다고 생각하는데
HTTP 네트워킹의 경우는 단발성이라고 생각하고 있긴 합니다..

이건 iOS끼리 한 번 깊게 이야기 나눠보면 좋을 것 같네요 😊

2023-11-18 15:23 UTC, SwiftyJunnos commented on iOS/MSCoreKit/Sources/MSNetworking/MSNetworking.swift
> +                let value = try JSONDecoder().decode(T.self, from: result.data)
```swift
JSONDecoder().decode(T.self, from: result.data)
```

이 형태가 조금 안예쁘긴 한 것 같아서

```swift
let decoder = JSONDecoder()
let value = try decoder.decode(T.self, from: result.data)
```

차라리 이런 형태는 어떠신가요?

---

프로퍼티로 빼는 건에 대해서는
만약에 `prettyPrinted` 같이 옵션을 줘야하는 상황이라면 구조체에 두고 지속적으로 사용해주는 것이 좋을 수도 있을 것 같아요.
그러면 통일성을 위해서 다른 곳에서도 빼두는 게 좋다고 생각합니다.

프로퍼티로 빼지 않는다면 위의 예시와 같이 별 다른 옵션 없이 바로 사용하는 편이 좋다고 생각합니다.
그런데 옵션을 줄 일 자체가 별로 없긴 하더라구요..

2023-11-20 08:50 UTC, yoondj98 requested changes
Test 코드까지 작성해두셨군요..!👍🏻👍🏻
일부 수정해야 할 부분과 비동기 구현 관련 의견 남겨두었습니다.
감사합니다!

2023-11-20 08:50 UTC, yoondj98 commented on iOS/MSCoreKit/Sources/MSNetworking/MSNetworking.swift
> +    func request<T: Decodable>(requestable: Requestable, type: T.Type) -> AnyPublisher<T, Error>? {
상황에 따라 다른 방식으로 구현하는 것과 통일된 방식으로 비동기 핸들링을 하는 것 중 고민이신가보네요..!
개인적으론 각 상황에 맞게 짜는 코드라는 점에서 창준님의 말씀도 꽤 일리가 있어서 좋을 것 같네요!

2023-11-20 08:50 UTC, yoondj98 commented on iOS/MSCoreKit/Sources/MSNetworking/DTO/Fragment/SpotDTO.swift
> +    let cooredinate: [[Double]]
```suggestion
    let coordinate: [Double]
```

2023-11-21 13:11 UTC, SwiftyJunnos approved these changes

2023-11-21 13:12 UTC, yoondj98 approved these changes

2023-11-23 15:19 UTC, merged