[iOS] TextField UIComponent 구현
boostcampwm2023/iOS01-MusicSpot pull request #88
Opened 2023-11-21 14:59 UTC by PushedGun

## ❗ 배경
> 작업 배경에 대한 설명을 작성합니다.
> Issue에 대한 링크를 첨부합니다.
#41 

## 🔧 작업 내역
> 작업한 내용들을 나열합니다.
> 간결하게 리스트 업하고, 자세한 설명은 아래 리뷰 노트에서 합니다.
### MSTextField 구현
### 버그 픽스 및 간단한 수정

## 🧪 테스트 방법
> 동작을 테스트할 수 있는 방법을 설명합니다.
> 앱 실행 방법일 수 있고, 유닛 테스트 실행 방법일 수 있습니다.

사용 예시
```swift
    let textField: MSTextField = {
        let textField = MSTextField()
        //원하는 이미지를 가진 textField 선택. (자세한 내용 하단 기재)
        textField.imageStyle = .none

        //필요 시 placeholder 및 text 작성
        textField.placeholder = "플레이스 홀더"
        textField.text = "필요시 작성"
        return textField
    }()
```
imageStyle이라는 enum 타입을 사용해, 아래 스크린 샷의 각기 다른 이미지를 가진 textField들을 구분할 수 있도록 하였습니다.

```swift
    public enum ImageStyle {
        
        case none
        case search
        case pin
        case calender
        case lock

    }
```
위 예시처럼, 사용 시 선언해주시면 됩니다.

## 📝 리뷰 노트
> 작업 내역에 대한 자세한 설명을 작성합니다.
### MSTextField 구현

### 버그 픽스 및 간단한 수정
- MSFont
: 객체로 반환하던 함수를, 옵셔널로 반환하게끔 수정하였습니다.

- MSIcon
: calender Icon의 불러오기에 문제가 발생하여 내부 파일을 수정하였습니다.
: UIImage로 반환할 때 항상 템플릿 렌더링을 사용하여 반환해주도록 하였습니다.

## 📸 스크린샷
> 작업한 내용에 대한 스크린샷, 영상 등을 첨부합니다.
<img width="243" alt="image" src="https://github.com/boostcampwm2023/iOS01-MusicSpot/assets/111111595/d5a73dcf-c8cb-4fb7-97d4-5f01993a067e">
<img width="246" alt="image" src="https://github.com/boostcampwm2023/iOS01-MusicSpot/assets/111111595/9bd75221-d794-42ea-be76-0626db0c7a78">

2023-11-21 15:35 UTC, SwiftyJunnos commented
혹시 폰트 사용하시기 전에 `MSFont.registerFonts()` 메서드 호출 하셨었나요?

2023-11-22 05:45 UTC, SwiftyJunnos requested changes
오른쪽에 화살표는 이전 디자인의 잔재인데 말씀을 안드렸었네요 😅 죄송합니다
다행히 알아서 잘 빼고 구현해주신 것 같아요

레이아웃 쪽이랑 함수 호출 쪽에도 `self`가 빠진 것들이 있어서 그거까지 수정해주시면 감사하겠습니다 🙌

2023-11-22 05:45 UTC, SwiftyJunnos commented on iOS/MSUIKit/Sources/MSUIKit/MSTextField/MSTextField.swift
> +    }
지우기 버튼은 UITextField에 기본으로 있는 `clearButtonMode` 사용하셔도 될 것 같아요!

https://developer.apple.com/documentation/uikit/uitextfield/viewmode

2023-11-22 05:45 UTC, SwiftyJunnos commented on iOS/MSUIKit/Sources/MSDesignSystem/MSFont.swift
>      }
이거 제 생각엔 폰트를 못 찾아서 기본 폰트로 적용되고 계실 것 같아요..!

`MSFont.registerFonts` 한 전 적용하고 이전 버전으로
한 번 확인 부탁드립니다

2023-11-22 05:45 UTC, SwiftyJunnos commented on iOS/MSUIKit/Sources/MSDesignSystem/MSIcon.swift
> +    case calendar = "Calender"
요거 파일 이름을 바꾸는게 어떨까요?

2023-11-22 05:45 UTC, SwiftyJunnos commented on iOS/MSUIKit/Sources/MSUIKit/MSTextField/MSTextField.swift
> +    private func placeholderConfigureLayout() {
```suggestion
    private func configurePlaceholderLayout() {
```

2023-11-22 05:45 UTC, SwiftyJunnos commented on iOS/MSUIKit/Sources/MSUIKit/MSTextField/MSTextField.swift
> +    private func leftPlaceholderConfigureLayout() {
```suggestion
    private func configureLeftPlaceholderLayout() {
```

2023-11-22 05:45 UTC, SwiftyJunnos commented on iOS/MSUIKit/Sources/MSUIKit/MSTextField/MSTextField.swift
> +    private func rightPlaceholderConfigureLayout() {
```suggestion
    private func configureRightPlaceholderLayout() {
```

2023-11-22 05:45 UTC, SwiftyJunnos commented on iOS/MSUIKit/Sources/MSUIKit/MSTextField/MSTextField.swift
> +        print(self.subviews)
```suggestion
```

2023-11-22 07:00 UTC, PushedGun commented on iOS/MSUIKit/Sources/MSUIKit/MSTextField/MSTextField.swift
> +        print(self.subviews)
ㅋㅋㅋㅋ이건 죄송합니다;; 머쓱

2023-11-22 07:28 UTC, PushedGun commented on iOS/MSUIKit/Sources/MSDesignSystem/MSFont.swift
>      }
앗.. 제가 UIFont PR을 꼼꼼히 확인해보지 못했군요.

2023-11-22 07:36 UTC, PushedGun commented on iOS/MSUIKit/Sources/MSUIKit/MSTextField/MSTextField.swift
> +    }
지우기 버튼 로직에 시간이 좀 걸렸는데 이런 기능이 있었군요..!

<img width="390" alt="image" src="https://github.com/boostcampwm2023/iOS01-MusicSpot/assets/111111595/528d33fc-ae25-4716-92c8-00589b44eb25">

잠시 적용해보니, UI가 저희 UI랑 조금 다르더라구요.
잠시 구글링을 해보니 이미지 변경은 되지만 위치 커스텀에 한계가 있는 듯합니다.

기존 로직도 덜어내야해서 수정하더라도 우선순위를 뒤로 미루는 것이 좋을 것 같습니다.

2023-11-22 08:32 UTC, SwiftyJunnos commented on iOS/MSUIKit/Sources/MSUIKit/MSTextField/MSTextField.swift
> +    }
사실 디자인에 있는 것도 기본 컴포넌트 모양을 그대로 갖다 쓴거였는데
뭔가 좀 다른게 들어갔나 보군요..!?

로직만 잘 수행되면 상관없긴 합니다 ㅎㅎ

2023-11-23 15:24 UTC, SwiftyJunnos commented on iOS/MSUIKit/Sources/MSUIKit/MSTextField/MSTextField.swift
> +    //
```suggestion
    
    // MARK: - Properties
    
```

2023-11-23 15:56 UTC, SwiftyJunnos approved these changes
Foundation/CoreKit 내용이 여기까지 들어와버렸네요.. 😅
내용은 확인했습니다.

2023-11-23 15:58 UTC, yoondj98 approved these changes

2023-11-23 15:58 UTC, merged