🚚 (HomeMapScene): HomeMapScene에 대한 UI 및 Polyline 드로잉 구현
boostcampwm2023/iOS01-MusicSpot pull request #94
Opened 2023-11-22 23:21 UTC by yoondj98

## ❗ 배경
> 작업 배경에 대한 설명을 작성합니다.
> Issue에 대한 링크를 첨부합니다.

HomeMap Scene에 대한 UI 구현을 완료했습니다.

## 🔧 작업 내역
> 작업한 내용들을 나열합니다.
> 간결하게 리스트 업하고, 자세한 설명은 아래 리뷰 노트에서 합니다.

-[x]  MapKit 적용
-[x] HomeMap 내 우상단 3-Button View 구현
-[x] Polyline 실시간 위치 반영 드로잉
-[] 권한 부여 설정  -> 전체에 적용 필요

## 🧪 테스트 방법
> 동작을 테스트할 수 있는 방법을 설명합니다.
> 앱 실행 방법일 수 있고, 유닛 테스트 실행 방법일 수 있습니다.

package의 HomeMapViewController를 initialViewController로 설정하면 됩니다.

## 📝 리뷰 노트
> 작업 내역에 대한 자세한 설명을 작성합니다.

현재 MapKit을 기반으로 HomeMap Scene의 화면을 모두 그렸습니다.
퍼블리싱 외 현재 기능으로 구현이 필요한 것은
1. 기존 Design System 적용
2. 저장된 Polyline들에 대한 DTO 생성
3. 서버와의 연동
4. 3-Button에 대한 Navigator 설정
5. 시작 버튼에 대한 동작 구현

## 📸 스크린샷
> 작업한 내용에 대한 스크린샷, 영상 등을 첨부합니다.

| :-: |
| <img src="https://github.com/boostcampwm2023/iOS01-MusicSpot/assets/54929503/a454096d-fad6-47e9-9e7d-7cb69f667543" width="300"> |

2023-11-23 15:37 UTC, SwiftyJunnos commented on iOS/HomeMapScene/Sources/HomeMapScene/HomeMapButtonView.swift
> +final class HomeMapButtonView: UIView {
외부에 드러낼 부분들에 public 붙여주세요!

2023-11-23 15:37 UTC, SwiftyJunnos commented on iOS/HomeMapScene/Sources/HomeMapScene/HomeMapButtonView.swift
> +        configureLayout()
self가 다 빠져있습니다..!

2023-11-26 05:58 UTC, SwiftyJunnos requested changes

2023-11-26 05:58 UTC, SwiftyJunnos commented on iOS/Features/HomeMapScene/Sources/HomeMapScene/HomeMapButtonView.swift
> +//  Test
```suggestion
//  HomeMap
```

파일 헤더 수정 부탁드려용

저랑 민건님은 Scene을 붙이지 않았는데 이것도 한 번 정해야겠네요
Scene을 붙이는 쪽이 더 직관적인 것 같기도 합니다.

2023-11-26 05:58 UTC, SwiftyJunnos commented on iOS/Features/HomeMapScene/Sources/HomeMapScene/HomeMapButtonView.swift
> +    // MARK: - Properties
```suggestion
    // MARK: - UI Components
```

https://www.notion.so/musicspot/Swift-c80e89fdf4ee41209c7afaed3d759e82?pvs=4#2ca9bc36ba1640939eb82712e2db8b65

조금 헷갈리는 면이 있었던 것 같아서
MARK 컨벤션에 대한 예시를 추가해뒀습니다..!
한 번 확인 부탁드려요 😉

2023-11-26 05:58 UTC, SwiftyJunnos commented on iOS/Features/HomeMapScene/Sources/HomeMapScene/HomeMapButtonView.swift
> +        }
저희 최소 버전이 15.0 이상이라 13.0 이상에 대한 분기 처리는 하지 않아도 될 것 같아요!

2023-11-26 05:58 UTC, SwiftyJunnos commented on iOS/Features/HomeMapScene/Sources/HomeMapScene/HomeMapButtonView.swift
> +        spacing = 24  // vertical spacing between buttons
상수들은 `private enum Metric` 등의 방법으로 파일 상단에서 따로 관리 부탁드려요.

https://www.notion.so/musicspot/Swift-c80e89fdf4ee41209c7afaed3d759e82?pvs=4#f385b58a426245db892a244a52e2631b

2023-11-26 05:58 UTC, SwiftyJunnos commented on iOS/Features/HomeMapScene/Sources/HomeMapScene/HomeMapButtonView.swift
> +        addArrangedSubview(locationButton)
```suggestion
        [
            self.settingButton,
            self.mapButton,
            self.locationButton
        ].forEach {
            self.addArrangedSubview($0)
        }
```

민건님도 비슷한 방식을 사용하셨던데
여러 개를 동시에 처리할 일이 있다면 이렇게 `forEach`를 사용하면 가독성 측면에서 좋을 것 같아요.

2023-11-27 08:00 UTC, PushedGun requested changes
리뷰가 늦어 죄송합니다. 고생많으셨습니다!!

2023-11-30 12:43 UTC, SwiftyJunnos approved these changes
너무 옛날 코드가 아직까지 PR로 남아있었네요.
합치고 추가적으로 작업들 부탁드립니다!

2023-11-30 12:50 UTC, PushedGun approved these changes

2023-11-30 12:51 UTC, merged